In [98]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math
from sklearn.preprocessing import LabelEncoder
import word2number as w2n

In [97]:
df = pd.read_csv("C:\\Python Develop\\Python Dev\\Cognitive Computing & Learning Machines\\Machine Learning\\Linear Regression Multi-variable\\homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [73]:
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [74]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [75]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [17]:
# reg.fit(X,Y)

In [76]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [77]:
reg.intercept_

221323.00186540408

In [78]:
# reg.predict([[3300,4,20]])

C:\Anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([620050.22241355])

In [79]:
R=112.06244194*3300+23388.88007794*4-3231.71790863*20+221323.00186540408
R

620050.222406564

In [80]:
new_df = df.drop('price',axis='columns')
new_df

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [81]:
price = df.price
price

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [82]:
reg = linear_model.LinearRegression()
reg.fit(new_df,price)

LinearRegression()

In [45]:
reg.fit(new_df,price)

LinearRegression()

In [83]:
# IN=float(input())
# n=int(input())
age=int(input())
predicted_price = reg.predict([[3600,4,age]])
print('The predicted price for an area,age & no. of bedrooms of {IN},{n},{p} square feet is:',{predicted_price[0]})

 5


The predicted price for an area,age & no. of bedrooms of {IN},{n},{p} square feet is: {702144.7236256807}


C:\Anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [84]:
reg.predict([[3600,4,15]])

C:\Anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([669827.54453935])

# In exercise folder (same level as this notebook on github) there is hiring.csv. 
This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score.
Based on these 3 factors, HR will decide the salary. Given this data, 
you need to build a machine learning model for HR department that can help them decide salaries for future candidates. 
Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview sco

In [99]:
hiring = pd.read_csv("C:\\Python Develop\\Python Dev\\Cognitive Computing & Learning Machines\\Machine Learning\\Linear Regression Multi-variable\\hiring.csv")
hiring

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [100]:
test_score = math.floor(hiring.test_score.median())
test_score

8

In [88]:
median_test_score = math.floor(hiring['test_score'].mean())
median_test_score

7

In [101]:
hiring.test_score=hiring.test_score.fillna(test_score)
hiring

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [102]:
hiring.experience = hiring.experience.fillna("zero")
hiring

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [103]:
# hiring.experience = hiring.experience.apply(w2n.word_)
# hiring
hiring['experience'] = hiring['experience'].apply(w2n.word_to_num)
hiring

AttributeError: module 'word2number' has no attribute 'word_to_num'

In [104]:
hiring['experience'] = LabelEncoder().fit_transform(hiring['experience'])

# Display the transformed dataframe
hiring

experience  test_score  interview_score  salary
0           6         8.0                9   50000
1           6         8.0                6   45000
2           1         6.0                7   60000
3           5        10.0               10   65000
4           2         9.0                6   70000
5           4         7.0               10   62000
6           3         8.0                7   72000
7           0         7.0                8   80000

In [93]:
hiring.experience = hiring.experience.fillna(0)
hiring

experience  test_score  interview_score  salary
0           6         8.0                9   50000
1           6         8.0                6   45000
2           1         6.0                7   60000
3           5        10.0               10   65000
4           2         9.0                6   70000
5           4         7.0               10   62000
6           3         8.0                7   72000
7           0         7.0                8   80000

In [105]:
rg = linear_model.LinearRegression()
rg.fit(hiring[['experience','test_score','interview_score']],hiring.salary)

LinearRegression()

In [106]:
new_df = hiring.drop('salary',axis='columns')
new_df

experience  test_score  interview_score
0           6         8.0                9
1           6         8.0                6
2           1         6.0                7
3           5        10.0               10
4           2         9.0                6
5           4         7.0               10
6           3         8.0                7
7           0         7.0                8

In [107]:
Salary = hiring.salary
Salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [108]:
reg.fit(new_df,Salary)

LinearRegression()

In [111]:
# age=int(input())
Salary = rg.predict([[6,8,9]])
print('The predicted price for an area,age & no. of bedrooms of {IN},{n},{p} square feet is:',{Salary[0]})

The predicted price for an area,age & no. of bedrooms of {IN},{n},{p} square feet is: {51226.455102089436}


C:\Anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
